title: Just let me get to the fun part
author: MikelBai
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Here we go again...

# social links
twitter_username: your-twitter-handle
github_username:  MikelBai
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
